spring:
  cloud:
    function:
      definition: softInterrupt;request

cse-cc-runner:
  zone-id: "Europe/Paris"
  xnodes:
    file-path: /home/farao/xnodes/xnodes.xml
  outputs:
    final-cgm: FINAL_CGM
    ttc-rao: TTC_RAO