spring:
  application:
    name: cse-cc-export-runner
  rabbitmq:
    host: localhost
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 2400000
  cloud:
    function:
      definition: softInterrupt;request
    stream:
      default:
        binder: rabbit
      bindings:
        softInterrupt-in-0:
          destination: cse-x-stop-task # replace 'x' with the process
        request-in-0:
          destination: cse-x-request # replace 'x' with the process
          group: cse-x-runner # replace 'x' with the process
        request-out-0:
          destination: cse-x-response # replace 'x' with the process
        task-status-update:
          destination: cse-x-task-status-updated # replace 'x' with the process
        stop-rao:
          destination: stop-rao-runner

logback:
  amqp:
    exchange: task-manager-events
    routing-key: "#"

rao-runner-server:
  amqp:
    client-app-id: cse-cc-export-runner
    queue-name: rao-request-queue

minio-adapter:
  bucket: gridcapa
  base-path: ""
  access-key: gridcapa
  secret-key: gridcapa
  url: http://minio:9000

cse-cc-runner:
  zone-id: "Europe/Paris"
  outputs:
    final-cgm: FINAL_CGM
    ttc-rao: TTC_RAO
  xnodes:
    file-path: /home/farao/xnodes/xnodes.xml
  mendrisio:
    mendrisio-voltage-level: SMENDR3
    mendrisio-node-id: SMENDR3T
  pisa:
    link1:
      node-fr: FFG.IL12
      node-it: FFG.IL11
      fictive-lines:
        - FFG.IL12 FFG.IL11 1
        - FFG.IL12 FFG.IL11 2
    link2:
      node-fr: FFG.IL14
      node-it: FFG.IL13
      fictive-lines:
        - FFG.IL14 FFG.IL13 1
        - FFG.IL14 FFG.IL13 2
  whitelist:
    - http://minio:9000/
    - http://localhost:9000/