spring:
  cloud:
    function:
      definition: softInterrupt;request

cse-cc-runner:
  zone-id: "Europe/Paris"
  trm: 500
  default-max-dichotomies-number: 4
  outputs:
    initial-cgm: INITIAL_CGM
    final-cgm: FINAL_CGM
    ttc-res: TTC_RES
  xnodes:
    file-path: /home/farao/xnodes.xml
