spring:
  application:
    name: cse-cc-runner
  rabbitmq:
    host: localhost
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 2400000
  cloud:
    stream:
      function:
        definition: interrupt;request
      default:
        binder: rabbit
        group: cse-idcc-runner
      bindings:
        interrupt-in-0:
          destination: cse-interrupt
        request-in-0:
          destination: cse-import-idcc-request
        request-out-0:
          destination: cse-response
        task-status-update:
          destination: cse-import-idcc-task-status-updated

logback:
  amqp:
    exchange: task-manager-events
    routing-key: "#"

rao-runner-server:
  amqp:
    client-app-id: cse-cc-runner  # should be overridden with value of app name
    queue-name: rao-request-queue

minio-adapter:
  bucket: gridcapa
  base-path:
  access-key: gridcapa
  secret-key: gridcapa
  url: http://minio:9000

cse-cc-runner:
  zone-id: "Europe/Paris"
  trm: 500
  outputs:
    initial-cgm: INITIAL_CGM
    final-cgm: FINAL_CGM
    ttc-res: TTC_RES
  xnodes:
    file-path: /home/farao/xnodes.xml
  combined-ras:
    file-path: /home/farao/combinedRAs.json
  mendrisio:
    mendrisio-cagno-line:
      target-ch-id: ml_0001
      ntc-id: ml_mendrisio-cagno
    mendrisio-pst-id: SMENDR3T SMENDR32 1
    mendrisio-node-id: SMENDR3T
  pisa:
    link1:
      node-fr: FFG.IL12
      node-it: FFG.IL11
      fictive-lines:
        - FFG.IL12 FFG.IL11 1
        - FFG.IL12 FFG.IL11 2
    link2:
      node-fr: FFG.IL14
      node-it: FFG.IL13
      fictive-lines:
        - FFG.IL14 FFG.IL13 1
        - FFG.IL14 FFG.IL13 2
  whitelist:
    - http://minio:9000/
