name: CI - master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: master

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode -Pdefault,coverage install

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=farao-community
          -Dsonar.projectKey=farao-community_gridcapa-cse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build and publish Docker image for import corner
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: farao/gridcapa-cse-cc-import-runner
          username: farao
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ImportDockerfile

      - name: Build and publish Docker image for export corner
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: farao/gridcapa-cse-cc-export-runner
          username: farao
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ExportDockerfile
